### ISSUE TITLE
Bugs ved ny sesong

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMnetwork_admin#1]
- [x] Fylker med nordiske tegn får ikke basepath/siteurl/homedir
- [x] Fylker med nordiske tegn får feil passord (#3)
- [x] Lærdal og Lardal-brukerne må håndteres på noe vis? (#4)
- [ ] Rewrites feiler av ukjent grunn (#10)
- [x] Sett site_option season = ny sesong
- [x] Fylkesbrukere får ikke riktig standardsite (#2)
- [x] Passord blir ikke faktisk oppdatert (kun nordiske)
- [x] Fylkeskontakter får ikke nytt passord
- [x] Hovedsiden får feil sesong (og muligens også nettverket?)

**Comment by mariusmandal** [comment]
Fylker skrevet om til å bruke UKMapi::fylker
Lærdal og Lardal skal være ok så lenge begge ligger i databasen ved start (som det gjør nå)
